### ISSUE TITLE
Problem when using shouty in VPS

### ISSUE THREAD

**Issue by Feners4** [edne/shouty#10]
I was using shouty in local dev without any problems. When I move the flask app to a VPS, I am now getting the error `RuntimeError: Library shout not found` when I execute:

```
def streamRadio():
    with shouty.connect(**params) as connection:
        print(connection)
        with open('music.mp3', 'rb') as f:
            while True:
                chunk = f.read(4096)
                print(chunk)
                if not chunk:
                    break

                connection.send(chunk)
                connection.sync()
```

I'm confused whether this is a bug or a problem with my flask app.

**Comment by turlando** [comment]
Make sure you have `libshout` installed in your system.

**Comment by Feners4** [comment]
Thank you!
