### ISSUE TITLE
Login fails when Flask app connects to IceCast server on the same VPS

### ISSUE THREAD

**Issue by Feners4** [edne/shouty#11]
I set up a VPS to host a Flask app with a web player streaming music from an IceCast stream. In the Flask app I connect to the IceCast server with:

```
import shouty

params = {
    'host': 'x.x.x.x',
    'port': 8000,
    'user': 'source',
    'password': 'hackme',
    'format': shouty.Format.MP3,
    'mount': '/stream'
}

def streamRadio():
    with shouty.connect(**params) as connection:
        with open('music.mp3', 'rb') as f:
            while True:
                chunk = f.read(4096)
                if not chunk:
                    break

                connection.send(chunk)
                connection.sync()
```

For host I use the IP address of the VPS and I have the IP for hostname in `icecast.xml`.  For testing, I launch the Flask Dev Server and got to the VPS address `x.x.x.x:5000`. When the page loads with the web player, it tries to connect to the IceCast server using the `streamRadio()` function. This returns the error `Error description: Login failed`. I have tested running the Flask app on my computer and connecting to IceCast on the VPS and it worked. Is there something wrong with how I set up the parameter in the Flask app for the VPS?

**Comment by turlando** [comment]
If you're running Icecast on the same machine you could just use `127.0.0.1` or `localhost` as host.

Besides, I would check the Icecast logs too. The log directory is defined in `icecast.xml` under `<paths><logdir>`. Try also to use a different logging level under `<logging><loglevel>`.

**Comment by Feners4** [comment]
Looking at the error log I found:
```
[2020-10-06  13:22:34] INFO connection/_handle_source_request Source logging in at mountpoint "/stream" from 127.0.0.1
[2020-10-06  13:22:34] INFO connection/_handle_source_request Source (/stream) attempted to login with invalid or missing password
```
I'm still using the default settings in `icecast.xml`, so I don't understand why it would say invalid or missing password if I'm using `hackme` as the password for `source` user in my parameters?

**Comment by Feners4** [comment]
After looking more closely at the error log with the logging level 4, I saw that even after getting the `attempted to login with invalid or missing password` on the log, it would also show `DBUG connection/connection_complete_source sources count is 0`. The connection was being made after all.
